class QuranSurahModel {
  final int suraNumber;
  final String suraNameEn;
  final String suraNameAr;
  final int suraVerses;

  QuranSurahModel({
    required this.suraNumber,
    required this.suraNameEn,
    required this.suraNameAr,
    required this.suraVerses,
  });

  static List<QuranSurahModel> quranSurahList = [
  QuranSurahModel(suraNumber: 1, suraNameEn: 'Al-Fatiha', suraNameAr: 'الفاتحة', suraVerses: 7),
  QuranSurahModel(suraNumber: 2, suraNameEn: 'Al-Baqarah', suraNameAr: 'البقرة', suraVerses: 286),
  QuranSurahModel(suraNumber: 3, suraNameEn: 'Aal-E-Imran', suraNameAr: 'آل عمران', suraVerses: 200),
  QuranSurahModel(suraNumber: 4, suraNameEn: 'An-Nisa', suraNameAr: 'النساء', suraVerses: 176),
  QuranSurahModel(suraNumber: 5, suraNameEn: 'Al-Ma\'idah', suraNameAr: 'المائدة', suraVerses: 120),
  QuranSurahModel(suraNumber: 6, suraNameEn: 'Al-An\'am', suraNameAr: 'الأنعام', suraVerses: 165),
  QuranSurahModel(suraNumber: 7, suraNameEn: 'Al-A\'raf', suraNameAr: 'الأعراف', suraVerses: 206),
  QuranSurahModel(suraNumber: 8, suraNameEn: 'Al-Anfal', suraNameAr: 'الأنفال', suraVerses: 75),
  QuranSurahModel(suraNumber: 9, suraNameEn: 'At-Tawbah', suraNameAr: 'التوبة', suraVerses: 129),
  QuranSurahModel(suraNumber: 10, suraNameEn: 'Yunus', suraNameAr: 'يونس', suraVerses: 109),
  QuranSurahModel(suraNumber: 11, suraNameEn: 'Hud', suraNameAr: 'هود', suraVerses: 123),
  QuranSurahModel(suraNumber: 12, suraNameEn: 'Yusuf', suraNameAr: 'يوسف', suraVerses: 111),
  QuranSurahModel(suraNumber: 13, suraNameEn: 'Ar-Ra\'d', suraNameAr: 'الرعد', suraVerses: 43),
  QuranSurahModel(suraNumber: 14, suraNameEn: 'Ibrahim', suraNameAr: 'إبراهيم', suraVerses: 52),
  QuranSurahModel(suraNumber: 15, suraNameEn: 'Al-Hijr', suraNameAr: 'الحجر', suraVerses: 99),
  QuranSurahModel(suraNumber: 16, suraNameEn: 'An-Nahl', suraNameAr: 'النحل', suraVerses: 128),
  QuranSurahModel(suraNumber: 17, suraNameEn: 'Al-Isra', suraNameAr: 'الإسراء', suraVerses: 111),
  QuranSurahModel(suraNumber: 18, suraNameEn: 'Al-Kahf', suraNameAr: 'الكهف', suraVerses: 110),
  QuranSurahModel(suraNumber: 19, suraNameEn: 'Maryam', suraNameAr: 'مريم', suraVerses: 98),
  QuranSurahModel(suraNumber: 20, suraNameEn: 'Ta-Ha', suraNameAr: 'طه', suraVerses: 135),
  QuranSurahModel(suraNumber: 21, suraNameEn: 'Al-Anbiya', suraNameAr: 'الأنبياء', suraVerses: 112),
  QuranSurahModel(suraNumber: 22, suraNameEn: 'Al-Hajj', suraNameAr: 'الحج', suraVerses: 78),
  QuranSurahModel(suraNumber: 23, suraNameEn: 'Al-Mu\'minun', suraNameAr: 'المؤمنون', suraVerses: 118),
  QuranSurahModel(suraNumber: 24, suraNameEn: 'An-Nur', suraNameAr: 'النور', suraVerses: 64),
  QuranSurahModel(suraNumber: 25, suraNameEn: 'Al-Furqan', suraNameAr: 'الفرقان', suraVerses: 77),
  QuranSurahModel(suraNumber: 26, suraNameEn: 'Ash-Shu\'ara', suraNameAr: 'الشعراء', suraVerses: 227),
  QuranSurahModel(suraNumber: 27, suraNameEn: 'An-Naml', suraNameAr: 'النمل', suraVerses: 93),
  QuranSurahModel(suraNumber: 28, suraNameEn: 'Al-Qasas', suraNameAr: 'القصص', suraVerses: 88),
  QuranSurahModel(suraNumber: 29, suraNameEn: 'Al-Ankabut', suraNameAr: 'العنكبوت', suraVerses: 69),
  QuranSurahModel(suraNumber: 30, suraNameEn: 'Ar-Rum', suraNameAr: 'الروم', suraVerses: 60),
  QuranSurahModel(suraNumber: 31, suraNameEn: 'Luqman', suraNameAr: 'لقمان', suraVerses: 34),
  QuranSurahModel(suraNumber: 32, suraNameEn: 'As-Sajda', suraNameAr: 'السجدة', suraVerses: 30),
  QuranSurahModel(suraNumber: 33, suraNameEn: 'Al-Ahzab', suraNameAr: 'الأحزاب', suraVerses: 73),
  QuranSurahModel(suraNumber: 34, suraNameEn: 'Saba', suraNameAr: 'سبأ', suraVerses: 54),
  QuranSurahModel(suraNumber: 35, suraNameEn: 'Fatir', suraNameAr: 'فاطر', suraVerses: 45),
  QuranSurahModel(suraNumber: 36, suraNameEn: 'Ya-Sin', suraNameAr: 'يس', suraVerses: 83),
  QuranSurahModel(suraNumber: 37, suraNameEn: 'As-Saffat', suraNameAr: 'الصافات', suraVerses: 182),
  QuranSurahModel(suraNumber: 38, suraNameEn: 'Sad', suraNameAr: 'ص', suraVerses: 88),
  QuranSurahModel(suraNumber: 39, suraNameEn: 'Az-Zumar', suraNameAr: 'الزمر', suraVerses: 75),
  QuranSurahModel(suraNumber: 40, suraNameEn: 'Ghafir', suraNameAr: 'غافر', suraVerses: 85),
  QuranSurahModel(suraNumber: 41, suraNameEn: 'Fussilat', suraNameAr: 'فصلت', suraVerses: 54),
  QuranSurahModel(suraNumber: 42, suraNameEn: 'Ash-Shura', suraNameAr: 'الشورى', suraVerses: 53),
  QuranSurahModel(suraNumber: 43, suraNameEn: 'Az-Zukhruf', suraNameAr: 'الزخرف', suraVerses: 89),
  QuranSurahModel(suraNumber: 44, suraNameEn: 'Ad-Dukhan', suraNameAr: 'الدخان', suraVerses: 59),
  QuranSurahModel(suraNumber: 45, suraNameEn: 'Al-Jathiya', suraNameAr: 'الجاثية', suraVerses: 37),
  QuranSurahModel(suraNumber: 46, suraNameEn: 'Al-Ahqaf', suraNameAr: 'الأحقاف', suraVerses: 35),
  QuranSurahModel(suraNumber: 47, suraNameEn: 'Muhammad', suraNameAr: 'محمد', suraVerses: 38),
  QuranSurahModel(suraNumber: 48, suraNameEn: 'Al-Fath', suraNameAr: 'الفتح', suraVerses: 29),
  QuranSurahModel(suraNumber: 49, suraNameEn: 'Al-Hujurat', suraNameAr: 'الحجرات', suraVerses: 18),
  QuranSurahModel(suraNumber: 50, suraNameEn: 'Qaf', suraNameAr: 'ق', suraVerses: 45),
  QuranSurahModel(suraNumber: 51, suraNameEn: 'Adh-Dhariyat', suraNameAr: 'الذاريات', suraVerses: 60),
  QuranSurahModel(suraNumber: 52, suraNameEn: 'At-Tur', suraNameAr: 'الطور', suraVerses: 49),
  QuranSurahModel(suraNumber: 53, suraNameEn: 'An-Najm', suraNameAr: 'النجم', suraVerses: 62),
  QuranSurahModel(suraNumber: 54, suraNameEn: 'Al-Qamar', suraNameAr: 'القمر', suraVerses: 55),
  QuranSurahModel(suraNumber: 55, suraNameEn: 'Ar-Rahman', suraNameAr: 'الرحمن', suraVerses: 78),
  QuranSurahModel(suraNumber: 56, suraNameEn: 'Al-Waqia', suraNameAr: 'الواقعة', suraVerses: 96),
  QuranSurahModel(suraNumber: 57, suraNameEn: 'Al-Hadid', suraNameAr: 'الحديد', suraVerses: 29),
  QuranSurahModel(suraNumber: 58, suraNameEn: 'Al-Mujadila', suraNameAr: 'المجادلة', suraVerses: 22),
  QuranSurahModel(suraNumber: 59, suraNameEn: 'Al-Hashr', suraNameAr: 'الحشر', suraVerses: 24),
  QuranSurahModel(suraNumber: 60, suraNameEn: 'Al-Mumtahana', suraNameAr: 'الممتحنة', suraVerses: 13),
  QuranSurahModel(suraNumber: 61, suraNameEn: 'As-Saff', suraNameAr: 'الصف', suraVerses: 14),
  QuranSurahModel(suraNumber: 62, suraNameEn: 'Al-Jumua', suraNameAr: 'الجمعة', suraVerses: 11),
  QuranSurahModel(suraNumber: 63, suraNameEn: 'Al-Munafiqoon', suraNameAr: 'المنافقون', suraVerses: 11),
  QuranSurahModel(suraNumber: 64, suraNameEn: 'At-Taghabun', suraNameAr: 'التغابن', suraVerses: 18),
  QuranSurahModel(suraNumber: 65, suraNameEn: 'At-Talaq', suraNameAr: 'الطلاق', suraVerses: 12),
  QuranSurahModel(suraNumber: 66, suraNameEn: 'At-Tahrim', suraNameAr: 'التحريم', suraVerses: 12),
  QuranSurahModel(suraNumber: 67, suraNameEn: 'Al-Mulk', suraNameAr: 'الملك', suraVerses: 30),
  QuranSurahModel(suraNumber: 68, suraNameEn: 'Al-Qalam', suraNameAr: 'القلم', suraVerses: 52),
  QuranSurahModel(suraNumber: 69, suraNameEn: 'Al-Haqqah', suraNameAr: 'الحاقة', suraVerses: 52),
  QuranSurahModel(suraNumber: 70, suraNameEn: 'Al-Ma\'arij', suraNameAr: 'المعارج', suraVerses: 44),
  QuranSurahModel(suraNumber: 71, suraNameEn: 'Nuh', suraNameAr: 'نوح', suraVerses: 28),
  QuranSurahModel(suraNumber: 72, suraNameEn: 'Al-Jinn', suraNameAr: 'الجن', suraVerses: 28),
  QuranSurahModel(suraNumber: 73, suraNameEn: 'Al-Muzzammil', suraNameAr: 'المزمل', suraVerses: 20),
  QuranSurahModel(suraNumber: 74, suraNameEn: 'Al-Muddathir', suraNameAr: 'المدثر', suraVerses: 56),
  QuranSurahModel(suraNumber: 75, suraNameEn: 'Al-Qiyamah', suraNameAr: 'القيامة', suraVerses: 40),
  QuranSurahModel(suraNumber: 76, suraNameEn: 'Al-Insan', suraNameAr: 'الإنسان', suraVerses: 31),
  QuranSurahModel(suraNumber: 77, suraNameEn: 'Al-Mursalat', suraNameAr: 'المرسلات', suraVerses: 50),
  QuranSurahModel(suraNumber: 78, suraNameEn: 'An-Naba', suraNameAr: 'النبأ', suraVerses: 40),
  QuranSurahModel(suraNumber: 79, suraNameEn: 'An-Naziat', suraNameAr: 'النازعات', suraVerses: 46),
  QuranSurahModel(suraNumber: 80, suraNameEn: 'Abasa', suraNameAr: 'عبس', suraVerses: 42),
  QuranSurahModel(suraNumber: 81, suraNameEn: 'At-Takwir', suraNameAr: 'التكوير', suraVerses: 29),
  QuranSurahModel(suraNumber: 82, suraNameEn: 'Al-Infitar', suraNameAr: 'الإنفطار', suraVerses: 19),
  QuranSurahModel(suraNumber: 83, suraNameEn: 'Al-Mutaffifin', suraNameAr: 'المطففين', suraVerses: 36),
  QuranSurahModel(suraNumber: 84, suraNameEn: 'Al-Inshiqaq', suraNameAr: 'الإنشقاق', suraVerses: 25),
  QuranSurahModel(suraNumber: 85, suraNameEn: 'Al-Buruj', suraNameAr: 'البروج', suraVerses: 22),
  QuranSurahModel(suraNumber: 86, suraNameEn: 'At-Tariq', suraNameAr: 'الطارق', suraVerses: 17),
  QuranSurahModel(suraNumber: 87, suraNameEn: 'Al-Ala', suraNameAr: 'الأعلى', suraVerses: 19),
  QuranSurahModel(suraNumber: 88, suraNameEn: 'Al-Ghashiyah', suraNameAr: 'الغاشية', suraVerses: 26),
  QuranSurahModel(suraNumber: 89, suraNameEn: 'Al-Fajr', suraNameAr: 'الفجر', suraVerses: 30),
  QuranSurahModel(suraNumber: 90, suraNameEn: 'Al-Balad', suraNameAr: 'البلد', suraVerses: 20),
  QuranSurahModel(suraNumber: 91, suraNameEn: 'Ash-Shams', suraNameAr: 'الشمس', suraVerses: 15),
  QuranSurahModel(suraNumber: 92, suraNameEn: 'Al-Lail', suraNameAr: 'الليل', suraVerses: 21),
  QuranSurahModel(suraNumber: 93, suraNameEn: 'Ad-Duha', suraNameAr: 'الضحى', suraVerses: 11),
  QuranSurahModel(suraNumber: 94, suraNameEn: 'Ash-Sharh', suraNameAr: 'الشرح', suraVerses: 8),
  QuranSurahModel(suraNumber: 95, suraNameEn: 'At-Tin', suraNameAr: 'التين', suraVerses: 8),
  QuranSurahModel(suraNumber: 96, suraNameEn: 'Al-Alaq', suraNameAr: 'العلق', suraVerses: 19),
  QuranSurahModel(suraNumber: 97, suraNameEn: 'Al-Qadr', suraNameAr: 'القدر', suraVerses: 5),
  QuranSurahModel(suraNumber: 98, suraNameEn: 'Al-Bayyina', suraNameAr: 'البينة', suraVerses: 8),
  QuranSurahModel(suraNumber: 99, suraNameEn: 'Az-Zalzalah', suraNameAr: 'الزلزلة', suraVerses: 8),
  QuranSurahModel(suraNumber: 100, suraNameEn: 'Al-Adiyat', suraNameAr: 'العاديات', suraVerses: 11),
  QuranSurahModel(suraNumber: 101, suraNameEn: 'Al-Qariah', suraNameAr: 'القارعة', suraVerses: 11),
  QuranSurahModel(suraNumber: 102, suraNameEn: 'At-Takathur', suraNameAr: 'التكاثر', suraVerses: 8),
  QuranSurahModel(suraNumber: 103, suraNameEn: 'Al-Asr', suraNameAr: 'العصر', suraVerses: 3),
  QuranSurahModel(suraNumber: 104, suraNameEn: 'Al-Humazah', suraNameAr: 'الهمزة', suraVerses: 9),
  QuranSurahModel(suraNumber: 105, suraNameEn: 'Al-Fil', suraNameAr: 'الفيل', suraVerses: 5),
  QuranSurahModel(suraNumber: 106, suraNameEn: 'Quraysh', suraNameAr: 'قريش', suraVerses: 4),
  QuranSurahModel(suraNumber: 107, suraNameEn: 'Al-Ma\'un', suraNameAr: 'الماعون', suraVerses: 7),
  QuranSurahModel(suraNumber: 108, suraNameEn: 'Al-Kawthar', suraNameAr: 'الكوثر', suraVerses: 3),
  QuranSurahModel(suraNumber: 109, suraNameEn: 'Al-Kafirun', suraNameAr: 'الكافرون', suraVerses: 6),
  QuranSurahModel(suraNumber: 110, suraNameEn: 'An-Nasr', suraNameAr: 'النصر', suraVerses: 3),
  QuranSurahModel(suraNumber: 111, suraNameEn: 'Al-Masad', suraNameAr: 'المسد', suraVerses: 5),
  QuranSurahModel(suraNumber: 112, suraNameEn: 'Al-Ikhlas', suraNameAr: 'الإخلاص', suraVerses: 4),
  QuranSurahModel(suraNumber: 113, suraNameEn: 'Al-Falaq', suraNameAr: 'الفلق', suraVerses: 5),
  QuranSurahModel(suraNumber: 114, suraNameEn: 'An-Nas', suraNameAr: 'الناس', suraVerses: 6),
  ];
}
